### ISSUE TITLE
Some doubts?

### ISSUE THREAD

**Issue by Jiongyu** [mikekaram/ether_ros#1]
can run in the kernel 4.15?
can you give same example about control slave such like mapping pdo etc?

**Comment by mikekaram** [comment]
Hi Jiongyu. Right now no, you can not run it on 4.15 kernel.

**Comment by mikekaram** [comment]
For mapping pdos, you can look at the source files input_pdo_publisher.cpp and output_pdo_publisher.cpp. 

Detailed information about the Output and Input EtherCAT variables can be found in pp. 126-128 in [this url](http://artemis.cslab.ece.ntua.gr:8080/jspui/bitstream/123456789/17313/3/thesis_final_Karamousadakis_Michail_03113030.pdf).

If you don't have anything else, I'm closing this issue.
